// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"HIME_GameOverEvents","status":true,"description":"v1.2 - Allows you to use events to set up a game over event.","parameters":{"Gameover Map ID":"18"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"BOB_BattleCommandList","status":true,"description":"Allows further customization of battle command menus by class\r\nand actor.","parameters":{"Force Default Commands":"1","Show Help Window":"1","Help Window Position":"2","Show Icons":"1","Icon Padding":"0","Help Window X":"-1","Help Window Y":"-1","Help Window Height":"-1","Help Window Width":"-1"}}
];
