// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"HIME_GameOverEvents","status":true,"description":"v1.2 - Allows you to use events to set up a game over event.","parameters":{"Gameover Map ID":"18"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"BOB_BattleCommandList","status":true,"description":"Allows further customization of battle command menus by class\r\nand actor.","parameters":{"Force Default Commands":"1","Show Help Window":"1","Help Window Position":"2","Show Icons":"1","Icon Padding":"0","Help Window X":"-1","Help Window Y":"-1","Help Window Height":"-1","Help Window Width":"-1"}},
{"name":"TDDP_FluidTimestep","status":true,"description":"1.0.2 Fixes MV's framerate dependent timestepping. Makes the gamespeed the same regardless of framerate.","parameters":{}},
{"name":"TDDP_NoFastForward","status":true,"description":"2.1.0 Disables the ability to fast forward move routes and/or text.                                                          id:TDDP_NoFastForward","parameters":{"Disable for Move Routes":"true","Disable for Show Text":"true"}},
{"name":"TDDP_PreloadManager","status":true,"description":"1.1.1 Preload resources on scene/map load as well as game startup for a smoother gameplay experience.          id:TDDP_PreloadManager","parameters":{"Preload On Map Load":"true","Preload System Music":"true","Preload System SFX":"true","Print Debug to Console":"false"}}
];
